server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gatway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

# 映射规则
zuul:
  routes:
#    服务器名称
    MICROSERVICECLOUD:
#      虚拟路径
      path: /mydept/**
#      真是地址
      serviceId: MICROSERVICECLOUD
  ignored-services: microservicecloud
  prefix: /nianzuochen


info:
  app-name: microservicecloud
  company-name: www.nianzuochen.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}