server:
  port: 8003

spring:
  application:
    name: microservicecloud
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB03?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept-8003
    prefer-ip-address: true

info:
  app-name: microservicecloud
  company-name: www.nianzuochen.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}